% big_medit2.pl

main :-
write("Starting program."),
retractall(b(_)),assertz(b(0)),

%prompt_meditator_n(CL),
%meditation1(Utterances1,Utterances2,Immortality),

%length(Utterances1,UL1),
%length(Utterances2,UL2),

%length(Immortality,J2),

% breasonings:

N1 is 	1 +						% meditation
		1 +						% texttobr2_square
		%1 + 					% 160 combophil br
		15 +		 			% d.sh
		%1 + 					% day2.sh 
								% with medit, tt, medic frozen age, 
								% hq thought
		1 +	%for CL				% a15_meditators.sh prepares an apartment 
								% in each dimension for meditators by 
								% helping 15 of those around them
		
		1, %for UL1+UL2,J2		% daily_medit.sh

GM is 	1, % for CL,				% group_meditation.sh

C1 is	GM +					
		1,						% time_hop.sh
C2 is	GM,

		bc12a,
		destination(N1,C1,C2,"Going to present"),
		destination(N1,C1,C2,"Going to 5689"),
		point_to_br(N1),
		prompt_question,
		anti_moral_end_meditators,
write("Finished program."),	
b(B),writeln(B),
		!.
		
prompt_meditation :-
write("Please think of 108 arems and 108 friendlinesses."),
%read_string(S),
%S="y",
!.

/*prompt_meditator_n(N) :-
repeat,write("Please enter the number of meditators (i.e. 1+)":"),
read_string(user_input,"\n\r","\n\r",_,S),
number_string(N,S),!.
*/
anti_moral_end_meditators:-
bc12(4). % 3 for a return time travel hop, 1 for CL

prompt_question :-
write("Please ask the future Head of State and the Simulation Co-ordinator for A, B, B to B for Anti-ageing medicine."),
%read_string(S),
%S="y",
!.




bc12a :-
bc12(2),
!.

point_to_br(T) :-
	bc12(T),!.

destination(N1,C1,C2,Label) :-
		point_to_br(N1),
		prompt_question,
		prompt_meditation,
		write(Label),prompt_tt,
		point_to_br(C1),
		bc12a,
		point_to_br(C2),
		prompt_meditation,!.
		
prompt_tt :- write(" "),
write("Please time travel now.")
%read_string(S),
%S="y"
,!.		

/*meditation1(Utterances1,Utterances2,Immortality) :-

	Utterances1=[%%dailyregimen and noheadaches,
	time_travel,mind_reading,medicine,meditation,fish_oil,
	
	tt_loc_one_to_two,tt_loc_two_to_three,tt_loc_three_to_one,
a_for_love_head_of_state,b_for_love_head_of_state,b_to_b_for_love_head_of_state,
a_for_immortality,b_for_immortality,b_to_b_for_immortality,
a_for_body_replacement,b_for_body_replacement,b_to_b_for_body_replacement,
a_for_immortality_medicine_for_thinking,b_for_immortality_medicine_for_thinking,b_to_b_for_immortality_medicine_for_thinking,
a_for_immortality_medicine_for_stopping_dementia,b_for_immortality_medicine_for_stopping_dementia,b_to_b_for_immortality_medicine_for_stopping_dementia,
a_for_immortality_medicine_for_seeing_clearly,b_for_immortality_medicine_for_seeing_clearly,b_to_b_for_immortality_medicine_for_seeing_clearly,
a_for_immortality_medicine_for_muscle_relaxation,b_for_immortality_medicine_for_muscle_relaxation,b_to_b_for_immortality_medicine_for_muscle_relaxation,
a_for_immortality_medicine_for_antidepressant,b_for_immortality_medicine_for_antidepressant,b_to_b_for_immortality_medicine_for_antidepressant,
a_for_immortality_medicine_for_antipsychotic,b_for_immortality_medicine_for_antipsychotic,b_to_b_for_immortality_medicine_for_antipsychotic,
a_for_other_medicines_for_the_body,b_for_other_medicines_for_the_body,b_to_b_for_other_medicines_for_the_body,
a_for_the_other_as,b_for_the_other_as,b_to_b_for_the_other_as,
a_for_thank_head_of_state,b_for_thank_head_of_state,b_to_b_for_thank_head_of_state,	
	

	connect_what_i_say_and_the_question,the_adverse,knock_out_cancer_frequency,i_am_serious,rod_off,good_circulation,no_smells,knock_out_annoying_frequency,knock_out_nagging_frequency,knock_out_complaining_frequency,stop_pain_inflammation_help_blood_flow_relaxation_and_wellbeing_and_deeptissue_massage
,memory,learning,no_cancer,comments,i_do_not_mean_it,law_to_protect_product,krishna_rcawp_for_wanted_people,say_reason_to_them,wanted_otherwise_dismissed,graciously_give_as, royalty, royalty_about_sales, nothing_rather_than_something,to_lucian,to_god,to_lecturer,today,tomorrow,day_after_tomorrow,a,b,b_to_b,seen_as_version,high_quality_version,army_go,army_return,
		no_digestive_system_pops_from_practising_the_sutra,
first_radio_button_put_on_recordings_put_through_with_pray_nut_and_bolt_quantum_box_prayer_for_protector_from_headache_in_meditation_after_honours_study,
second_radio_button_put_on_recordings_put_through_with_pray_nut_and_bolt_quantum_box_prayer_for_protector_from_headache_in_meditation_after_honours_study,
first_radio_button_put_on_recordings_put_through_with_pray_nut_and_bolt_quantum_box_prayer_for_no_headache,
second_radio_button_put_on_recordings_put_through_with_pray_nut_and_bolt_quantum_box_prayer_for_no_headache,
first_radio_button_put_on_recordings_put_through_with_pray_nut_and_bolt_quantum_box_prayer_for_turn_off_workload_from_all_employees_including_you_below_you,
second_radio_button_put_on_recordings_put_through_with_pray_nut_and_bolt_quantum_box_prayer_for_turn_off_workload_from_all_employees_including_you_below_you,
lecturer_training,
recordings_training,
prepare_the_radio_button_accredited__at_the_time__turned_off_openbracket_to_make_accreditation_acceptable_closebracket_computer_science__breathsoned__vocational_education_and_training__sales__education_for_the_following,
seen_as_breasoning_out_text_before_texttobr__computer_housing_the_breasonings__70_breasonings_per_waking_hour_for_16_hours__stopping_at_midnight__no_medical_problems_from_it,
put_through_prepared_radio_button,
put_through_250_word_breasonings_from_job_medicine_to_start_the_spiritual_breasoning_process,
turn_off_mistakes,
turn_off_breasonings,
first_radio_button_put_on_recordings_put_through_with_pray_nut_and_bolt_quantum_box_prayer_for_detect_and_turn_off_workloads_using_manager_algorithm,
second_radio_button_put_on_recordings_put_through_with_pray_nut_and_bolt_quantum_box_prayer_for_detect_and_turn_off_workloads_using_manager_algorithm,
first_radio_button_put_on_recordings_put_through_with_pray_nut_and_bolt_quantum_box_prayer_for_detect_and_turn_off_workloads_using_manager_network,
second_radio_button_put_on_recordings_put_through_with_pray_nut_and_bolt_quantum_box_prayer_for_detect_and_turn_off_workloads_using_manager_network,first_radio_button_put_on_recordings_put_through_with_pray_nut_and_bolt_quantum_box_prayer_for_no_muscle_aches_pains,
second_radio_button_put_on_recordings_put_through_with_pray_nut_and_bolt_quantum_box_prayer_for_no_muscle_aches_pains
],
	Utterances2=[
	medicine, 
	memory_receiver, memory_transmitter, use_memory_transmitter,
	fifty_As_per_organ,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_the_heart,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_heart_muscles,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_continually_circulating_blood_around_the_body,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_knowing_your_heart_is_working_because_you_can_feel_your_heart_beat,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_feeling_the_blood_at_your_pulse,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_pumping_blood_containing_new_oxygen_to_every_part_of_your_body,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_pumping_the_old_blood_without_oxygen_back_through_the_lungs_where_it_picks_up_new_oxygen_to_repeat_this_cycle,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_heart_function,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_the_heart_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_heart_muscles_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_continually_circulating_blood_around_the_body_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_knowing_your_heart_is_working_because_you_can_feel_your_heart_beat_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_feeling_the_blood_at_your_pulse_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_pumping_blood_containing_new_oxygen_to_every_part_of_your_body_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_pumping_the_old_blood_without_oxygen_back_through_the_lungs_where_it_picks_up_new_oxygen_to_repeat_this_cycle_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_heart_medicine,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_the_lungs,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_breathing,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_filtering_oxygen_from_the_air_through_tiny_vessels_into_the_blood,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_carrying_oxygen_to_the_heart_to_be_pumped_round_your_body,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_filtering_carbon_dioxide_from_your_body_when_you_breathe_out,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_lungs_function,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_the_lungs_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_breathing_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_filtering_oxygen_from_the_air_through_tiny_vessels_into_the_blood_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_carrying_oxygen_to_the_heart_to_be_pumped_round_your_body_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_filtering_carbon_dioxide_from_your_body_when_you_breathe_out_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_lungs_medicine,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_the_liver,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_filtering_the_blood,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_filtering_chemicals_and_impurities,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_including_from_drugs_and_medications,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_making_and_processes_many_body_fats_and_the_liver_regrowing,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_liver_function,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_the_liver_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_filtering_the_blood_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_filtering_chemicals_and_impurities_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_including_from_drugs_and_medications_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_making_and_processes_many_body_fats_and_the_liver_regrowing_should_be_kept_going_and_not_have_blocks_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_liver_medicine,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_the_kidneys,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_the_kidneys_filtering,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_filtering_some_drugs_and_filtering_waste_products_that_leave_the_body_as_urine,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_kidneys_function,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_the_kidneys_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_the_kidneys_filtering_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_filtering_some_drugs_and_filtering_waste_products_that_leave_the_body_as_urine_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_kidneys_medicine,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_the_stomach_and_intestines,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_starting_to_break_down_and_process_food__drink_and_oral_medications_in_the_body_and_absorbing_nutrients_and_drugs_through_the_stomach_and_small_intestine_walls,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_stomach_and_intestines_function,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_the_stomach_and_intestines_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_starting_to_break_down_and_process_food__drink_and_oral_medications_in_the_body_and_absorbing_nutrients_and_drugs_through_the_stomach_and_small_intestine_walls_should_be_kept_going_and_not_have_blocks_,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_stomach_and_intestines_medicine,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_the_thymus,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_developing_cdfour_cells_and_other_white_blood_cells,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_thymus_function,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_the_thymus_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_developing_cdfour_cells_and_other_white_blood_cells_should_be_kept_going_and_not_have_blocks_,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_thymus_medicine,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_the_pancreas,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_releasing_digestive_enzymes_into_the_small_intestine_and_hormones_that_control_sugar_levels_in_your_blood,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_in_that_case__living_without_a_pancreas_by_taking_insulin_to_regulate_blood_sugar_levels_and_taking_supplementary_digestive_enzymes,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_pancreas_function,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_the_pancreas_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_releasing_digestive_enzymes_into_the_small_intestine_and_hormones_that_control_sugar_levels_in_your_blood,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_in_that_case__living_without_a_pancreas_by_taking_insulin_to_regulate_blood_sugar_levels_and_taking_supplementary_digestive_enzymes_should_be_kept_going_and_not_have_blocks_,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_pancreas_medicine,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_the_skin,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_stopping_your_body_from_drying_out_and_being_the_main_barrier_against_infection,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_skin_function,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_the_skin_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_stopping_your_body_from_drying_out_and_being_the_main_barrier_against_infection_should_be_kept_going_and_not_have_blocks_,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_skin_medicine,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_the_bones,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_onezero_percent_of_bone_being_replaced_each_year,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_bones_function,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_the_bones_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_onezero_percent_of_bone_being_replaced_each_year_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_bones_medicine,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_bone_marrow,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_blood_cells_originally_coming_from_bone_marrow,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_bone_marrow_function,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_bone_marrow_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_blood_cells_originally_coming_from_bone_marrow_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_bone_marrow_medicine,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_blood,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_blood_pumped_by_your_heart,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_delivering_oxygen_and_nutrients_to_every_part_of_your_body_and_carrying_waste_products_away,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_blood_cells_openbracket_red_cells__white_cells__platelets_etc_closebracket_and_plasma,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_blood_function,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_blood_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_blood_pumped_by_your_heart_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_delivering_oxygen_and_nutrients_to_every_part_of_your_body_and_carrying_waste_products_away_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_blood_cells_openbracket_red_cells__white_cells__platelets_etc_closebracket_and_plasma_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_blood_medicine,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_plasma,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_its_nutrients__sugars__proteins__minerals__enzymes__and_other_substances_but_with_the_blood_cells_taken_out,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_plasma_function,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_plasma_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_its_nutrients__sugars__proteins__minerals__enzymes__and_other_substances_but_with_the_blood_cells_taken_out_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_plasma_medicine,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_lymph,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_its_white_blood_cells_and_antibodies,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_the_lymph_vessels__nodes__and_organs_and_removing_waste_products_from_the_body,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_lymph_function,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_lymph_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_its_white_blood_cells_and_antibodies_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_the_lymph_vessels__nodes__and_organs_and_removing_waste_products_from_the_body_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_lymph_medicine,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_the_lymph_nodes,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_the_cdfour_cells_in_your_body_resting_and_reproducing_in_your_lymph_nodes,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_lymph_nodes_function,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_the_lymph_nodes,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_the_cdfour_cells_in_your_body_resting_and_reproducing_in_your_lymph_nodes,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_lymph_nodes_medicine,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_organs__function,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_organs__medicine,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_your_heart_does_not_beat_unless_your_brain_and_nervous_system_tell_it_to_do_so,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_your_heart_beating_because_your_brain_and_nervous_system_tell_it_to_do_so_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_your_skeletal_system_relies_on_the_nutrients_it_gains_from_your_digestive_system_to_build_strong__healthy_bones,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_your_skeletal_system_relying_on_the_nutrients_it_gains_from_your_digestive_system_to_build_strong__healthy_bones_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_your_cardiovascular_system_works_to_circulate_your_blood,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_your_cardiovascular_system_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_your_respiratory_system_introduces_oxygen_into_your_body,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_your_respiratory_system_introducing_oxygen_into_your_body_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_your_heart_pumping_blood_through_a_complex_network_of_blood_vessels__your_blood_circulating_through_your_digestive_system_and_picking_up_nutrients_your_body_absorbed_from_your_last_meal__your_blood_carrying_oxygen_inhaled_by_the_lungs__your_circulatory_system_delivering_oxygen_and_nutrients_to_the_other_cells_of_your_body_picking_up_any_waste_products_created_by_these_cells_including_carbon_dioxide__and_delivering_these_waste_products_to_the_kidneys_and_lungs_for_disposal_and_the_circulatory_system_carrying_hormones_from_the_endocrine_system__and_the_immune_system_s_white_blood_cells_that_fight_off_infection,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_your_heart_pumping_blood_through_a_complex_network_of_blood_vessels__your_blood_circulating_through_your_digestive_system_and_picking_up_nutrients_your_body_absorbed_from_your_last_meal__your_blood_carrying_oxygen_inhaled_by_the_lungs__your_circulatory_system_delivering_oxygen_and_nutrients_to_the_other_cells_of_your_body_picking_up_any_waste_products_created_by_these_cells_including_carbon_dioxide__and_delivering_these_waste_products_to_the_kidneys_and_lungs_for_disposal_and_the_circulatory_system_carrying_hormones_from_the_endocrine_system__and_the_immune_system_s_white_blood_cells_that_fight_off_infection_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_your_respiratory_system_relying_on_your_circulatory_system_to_deliver_the_oxygen_it_gathers__the_muscles_of_your_heart_functioning_with_the_oxygen_they_receive_from_your_lungs__the_bones_of_your_skull_and_spine_protecting_your_brain_and_spinal_cord__your_brain_regulating_the_position_of_your_bones_by_controlling_your_muscles__the_circulatory_system_providing_your_brain_with_a_constant_supply_of_oxygen_rich_blood_and_your_brain_regulating_your_heart_rate_and_blood_pressure,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_your_respiratory_system_relying_on_your_circulatory_system_to_deliver_the_oxygen_it_gathers__the_muscles_of_your_heart_functioning_with_the_oxygen_they_receive_from_your_lungs__the_bones_of_your_skull_and_spine_protecting_your_brain_and_spinal_cord__your_brain_regulating_the_position_of_your_bones_by_controlling_your_muscles__the_circulatory_system_providing_your_brain_with_a_constant_supply_of_oxygen_rich_blood_and_your_brain_regulating_your_heart_rate_and_blood_pressure_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_your_skeletal_system_relying_on_your_urinary_system_to_remove_waste_produced_by_bone_cells__the_bones_of_your_skeleton_creating_structure_that_protects_your_bladder_and_other_urinary_system_organs__your_circulatory_system_delivers_oxygen_rich_blood_to_your_bones_and_your_bones_making_new_blood_cells,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_your_skeletal_system_relying_on_your_urinary_system_to_remove_waste_produced_by_bone_cells__the_bones_of_your_skeleton_creating_structure_that_protects_your_bladder_and_other_urinary_system_organs__your_circulatory_system_delivers_oxygen_rich_blood_to_your_bones_and_your_bones_making_new_blood_cells_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_working_together__these_systems_maintaining_internal_stability_and_balance__otherwise_known_as_homeostasis,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_working_together__these_systems_maintaining_internal_stability_and_balance__otherwise_known_as_homeostasis_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_organ_connections__function,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_organ_connections__medicine,

%%as degrees

reishi_mushroom, goji, ginseng, he_shou_wu, gotu_kola, schisandra, army, meditation_about_medicine_in_ayurveda, pedagogy_about_medicine_in_ayurveda, 

%%book args

doctor_sutra, meditation, protector_from_headache_in_meditation_currant_bun, meditation, panic_attack_prevented_by_deep_breathing_and_sutra, family_medicine, help_ensure_successful_conception_and_prevent_miscarriage, pedagogy, lucianic_pedagogical_medicine, pedagogy_grades_failure, pedagogy_course_plan, get_in_touch_with_god_about_breasonings_details_to_see_high_quality_imagery_and_earn_h_one, breasonings_two_hundred_and_fifty, preventing_sales_from_being_dangerous, perpetual_university_short_courses, apple_meditation_for_successful_relationship, miscellaneous, four_glasses_of_water_and_exercise_45_minutes_before_breakfast, go_to_bed_at_nine_thirty_pm, yoga_surya_namaskar1, yoga_surya_namaskar2, yoga_surya_namaskar3, yoga_surya_namaskar4, yoga_surya_namaskar5, yoga_surya_namaskar6, yoga_surya_namaskar7, yoga_surya_namaskar8, yoga_surya_namaskar9, yoga_surya_namaskar10, yoga_surya_namaskar11, yoga_surya_namaskar12, yoga_asanas1, yoga_asanas2, yoga_asanas3, yoga_asanas4, yoga_asanas5, yoga_asanas6, yoga_asanas7, yoga_asanas8, yoga_asanas9, yoga_asanas10, qigongbrocades1, qigongbrocades2, qigongbrocades3, qigongbrocades4, qigongbrocades5, qigongbrocades6, qigongbrocades7, qigongbrocades8, push_ups_shoulders, push_ups_chest, push_ups_triceps, push_ups_back, stomach_exercises_high_knee_taps, stomach_exercises_russian_twists, stomach_exercises_standing_bicycle_crunches, stomach_exercises_classic_plank, stomach_exercises_plank_knees_to_elbows, stomach_exercises_roll_up, stomach_exercises_rolling_like_a_ball, stomach_exercises_earthquake,immortality,

simulation,
 
supercard_or_any_number_of_as, 
work_out_with_250_breasonings_that_buying_a_product_from_my_time_represents_buying_a_product_to_the_future_, 
help_writers_of_secondary_texts_to_mine, 
help_primary_text_writers, 
help_businesses, 
the_computer_preferred_for_me_to_receive_rather_than_make_up_my_own_thoughts, 
warmth, 
food, 
shelter, 
i_chose_red_positive_not_blue_negative_thoughts, 
the_behaviour_that_led_to_no_disease_was_text_to_breasonings_about_meditation, 
my_body_was_replaced, 
the_building_which_looked_like_my_home_was_an_image_but_maintained_replaced_and_the_weather_surroundings_and_people_were_all_to_my_liking, 
heaven_on_earth_for_philosophers, 
time_travel_enables_immortality, 
people_in_the_simulation_came_back_to_the_real_world, 
i_mind_read_with_guru_dev_whether_it_was_safe_to_time_travel, 
i_could_buy_space_travel, 
my_consciousness_transferred_to_the_bot, 
invite_others_to_the_simulation,

consciousness,

prevent_headaches_on_train_and_a_bent_spine, brain, brain, brain_ii, maintain_dry_eyes, avoid_diseased_people, fewer_mental_breakdowns_schizophrenia, less_depression, honey_pot_prayer_for_no_headaches_in_cars_trains_and_walks, quantum_box_prayer, nut_and_bolt, head_of_state_head_ache_prevention, daily_regimen, laughter_for_depression, heart, contagious_diseases, berocca_prevents_colds_and_flu, food, grains_nuts_fruits_vegetables, sit_properly_at_table_during_meals, computational_english_argument, computational_english_is_like_a_calculator, intertextuality, finite_data_will_be_a_solution_in_conglish, radical_difference, order_in_conglish, dereconstruction, kolmogorov_hermeneutics, derivability, the_science_of_crossing_over, a_new_logic_reflecting_language_or_natural_logic, philosophical_computational_english, lenses, analysing_characteristics_of_arguments, conglish_reflection, narratology_diagram, how_can_the_program_cope_with_real_variation, subject_mix, perspectives, ratios, exploring_opposites_in_hamlet, drawing_connections, symbols, children___h_one____earning_jobs___protection_in_jobs, heads_of_state, lucian_mantra_pure_form, lucian_mantra_sun_safety, maharishi_sutra, meditation_teacher_sutra, moving_appearances, purusha, upasana_sutra, yellow_god, green_sutra, blue_nature, appearances, pranayama, soma, hours_prayer, fifty_breasonings_per_utterance, two_uses, x, y, breathsonings, rebreathsonings, room, part_of_room, direction, time_to_prepare, time_to_do, time_to_finish, professor_algorithm, god_algorithm, marking_scheme__humanities_and_science, marking_scheme__creative_arts, leadership, uses_for_money_in_theatre_studies, uses_for_money_in_epistemology_poetry, uses_for_money_in_music, uses_for_money_in_fine_arts, breasonings_currency, sales_for_lm_to_siva, marketing_for_lm_to_siva, breasoning_currency, lower_risk_of_cancer_and_other_diseases_in_workers_and_broadcasters, decreased_stress, increased_blood_flow, increased_brain_potential, higher_grades, fewer_stillbirths, a_greater_number_of_successful_job_applications, aigs_for_pedagogy_helper, accreditation, protectedness, areas_of_study_to_create_a_pedagogue, create_a_pedagogy_helper_for_the_student, finding_out_about_the_student_as_a_pedagogy_helper, daily_professional_requirement_of_the_pedagogy_helper, preparing_the_student_to_write_each_breasoning, pedagogy_helper__write_on_breasoning___politics, pedagogy_helper__write_on_breasoning___philosophy, pedagogy_helper__write_on_breasoning___computer_science, unification_to_become_pedagogy_helper, practicum, breason_out_arguments_twice_when_in_large_class, details, breasonings, rebreasoning, breathsoning, rebreathsoning, room, part_of_room, direction, time_to_prepare, time_to_do, time_to_finish, god_algorithm, professor_algorithm, marking_scheme__humanities, marking_scheme__creative_arts_and_science, gods_infallibility_from_being_critiqued, 

pedagogy, meditation, medicine, computational_english, business, theology, popology, societology, music, theatre_studies, time_travel,politics,

sales, professor, time_travel_in_place_now, berocca,

utterances_to_arems,
%%receptor_for_number_of_la_utterances_by_meditators,
%%transmitter_for_number_of_arems_to_meditators,
%%transmitted_number_of_arems_to_meditators,

%%qi_gong_receptor_for_muscle_aches_and_pains,
%%qi_gong_transmitter_for_prevention_muscle_aches_and_pains,
%%transmitted_qi_gong_prevention_muscle_aches_and_pains,

%%qi_gong_receptor_for_medicine,
%%qi_gong_transmitter_for_prevention_medicine,
%%transmitted_qi_gong_prevention_medicine,

%%ayur_veda_receptor_for_medicine,
%%ayur_veda_transmitter_for_prevention_medicine,
%%transmitted_ayur_veda_prevention_medicine,

%%receptor_for_breasonings,
%%transmitter_for_breasonings,
%%transmitted_breasonings,

%%receptor_for_sales,
%%transmitter_for_sales,
%%transmitted_sales,

dott_equals_250_breasonings_time_travel_with_10_algorithm_and_b_and_breasonings_text_describing_from_where_and_when_to_time_place_with_separate_radio_buttons_to_describe_breasonings_and_travel_stop_time_travel_safety_stop_time_travel_see_when_watched_stop_time_travel_no_depression_stop_time_travel_no_hole_in_my_character_at_the_start_stop_time_travel_hone_in_to_where_want_to_go_not_go_off_it_stop_time_travel_lead_comfortably__around_me_during_travel_for_no_anything_like_radiation_sickness_stop_time_travel_prevent_sickness_from_travelling_with_me_stop_time_travel_others_helped_to_find_my_time_travel_delightful__receptor_for_dott,
transmitter_for_dott,
transmitted_dott,

berocca,
%%receptor_for_need_of_berocca,
%%transmitter_for_need_of_berocca,
%%berocca_transmitted

i_love_the_robot_because_i_know_that_it_loves_me,

the_craft,

cosmology,

famousness_each_second,

give_bots_as,%%,

%%politics_give_as_when_departments_come_up
viagra_transmitter_if_necessary,

cast_with_it_over_answers,

sin_stopped,

port_thoughts,

b_to_bots_misbehaving, bots_help,

defend_mind_reading, defend_time_travel, defend_bots,

talk_to_copy_of_universe,
listen_to_copy_of_universe,
see_copy_of_universe,
appear_in_copy_of_universe,

give_people_who_i_see_5_as_over_5_days,

music_etc_number_one_education_help,

unfolding_of_bots_life,
sales_point_a_meditation_short_course,dot_on_sales_point_a_meditation_short_course,sales_point_b_meditation_short_course,dot_on_sales_point_b_meditation_short_course,sales_point_bb_meditation_short_course,dot_on_sales_point_bb_meditation_short_course,

sales_point_a_pedagogy_short_course,dot_on_sales_point_a_pedagogy_short_course,sales_point_b_pedagogy_short_course,dot_on_sales_point_b_pedagogy_short_course,sales_point_bb_pedagogy_short_course,dot_on_sales_point_bb_pedagogy_short_course,

sales_point_a_medicine_short_course,dot_on_sales_point_a_medicine_short_course,sales_point_b_medicine_short_course,dot_on_sales_point_b_medicine_short_course,sales_point_bb_medicine_short_course,dot_on_sales_point_bb_medicine_short_course,

sales_point_a_politics_short_course,dot_on_sales_point_a_politics_short_course,sales_point_b_politics_short_course,dot_on_sales_point_b_politics_short_course,sales_point_bb_politics_short_course,dot_on_sales_point_bb_politics_short_course,

sales_point_a_mindfulness_short_course,dot_on_sales_point_a_mindfulness_short_course,sales_point_b_mindfulness_short_course,dot_on_sales_point_b_mindfulness_short_course,sales_point_bb_mindfulness_short_course,dot_on_sales_point_bb_mindfulness_short_course,

sales_point_a_economics_short_course,dot_on_sales_point_a_economics_short_course,sales_point_b_economics_short_course,dot_on_sales_point_b_economics_short_course,sales_point_bb_economics_short_course,dot_on_sales_point_bb_economics_short_course,

sales_point_a_computer_science_short_course,dot_on_sales_point_a_computer_science_short_course,sales_point_b_computer_science_short_course,dot_on_sales_point_b_computer_science_short_course,sales_point_bb_computer_science_short_course,dot_on_sales_point_bb_computer_science_short_course,

sales_point_a_computational_english_short_course,dot_on_sales_point_a_computational_english_short_course,sales_point_b_computational_english_short_course,dot_on_sales_point_b_computational_english_short_course,sales_point_bb_computational_english_short_course,dot_on_sales_point_bb_computational_english_short_course,

three_plus_three_seconds_eye_direction1,
three_plus_three_seconds_eye_direction2,
three_plus_three_seconds_eye_direction3,
three_plus_three_seconds_eye_direction4,
three_plus_three_seconds_eye_direction5,
three_plus_three_seconds_eye_direction6,
three_plus_three_seconds_eye_direction7,
three_plus_three_seconds_eye_direction8,

lactobacillus_salivarius_massaged_into_teeth_and_gums_and_swallowed,

mucous_in_intestines_blocking_lactobacillus_salivarius_dissolved,

no_fluoride



],

Immortality=[

immortality_stasis_field,

big_idea_canceller,

bot_appears_to_age_normally,

bot_dies_at_80,

no_effect_of_eating_food_food_transported_directly_stomach,

no_other_effects_on_body,

no_early_death_from_tt,

mother_will_be_alive_to_cook_and_care_for_me,

friends_will_be_immortal,

no_natural_disasters_in_simulation,

partner_s_family_immortal,

really_different_looking_bot_in_simulation,

my_family_will_be_immortal,
a_for_reishi_mushroom,b_for_reishi_mushroom,b_to_b_for_reishi_mushroom,
a_for_goji,b_for_goji,b_to_b_for_goji,
a_for_ginseng,b_for_ginseng,b_to_b_for_ginseng,
a_for_he_shou_wu,b_for_he_shou_wu,b_to_b_for_he_shou_wu,
a_for_gotu_kola,b_for_gotu_kola,b_to_b_for_gotu_kola,
a_for_schisandra,b_for_schisandra,b_to_b_for_schisandra,
a_for_love_head_of_state,b_for_love_head_of_state,b_to_b_for_love_head_of_state,
a_for_thank_who_helped_me_with_immortality_medicine_body_replacement_and_anti_ageing,b_for_thank_who_helped_me_with_immortality_medicine_body_replacement_and_anti_ageing,b_to_b_for_thank_who_helped_me_with_immortality_medicine_body_replacement_and_anti_ageing,
a_for_thank_head_of_state_for_reishi_mushroom,b_for_thank_head_of_state_for_reishi_mushroom,b_to_b_for_thank_head_of_state_for_reishi_mushroom,
a_for_thank_head_of_state_for_goji,b_for_thank_head_of_state_for_goji,b_to_b_for_thank_head_of_state_for_goji,
a_for_thank_head_of_state_for_ginseng,b_for_thank_head_of_state_for_ginseng,b_to_b_for_thank_head_of_state_for_ginseng,
a_for_thank_head_of_state_for_he_shou_wu,b_for_thank_head_of_state_for_he_shou_wu,b_to_b_for_thank_head_of_state_for_he_shou_wu,
a_for_thank_head_of_state_for_gotu_kola,b_for_thank_head_of_state_for_gotu_kola,b_to_b_for_thank_head_of_state_for_gotu_kola,
a_for_thank_head_of_state_for_schisandra,b_for_thank_head_of_state_for_schisandra,b_to_b_for_thank_head_of_state_for_schisandra,
a_for_immortality,b_for_immortality,b_to_b_for_immortality,
a_for_body_replacement,b_for_body_replacement,b_to_b_for_body_replacement,
a_for_other_medicines_for_the_body,b_for_other_medicines_for_the_body,b_to_b_for_other_medicines_for_the_body,
a_for_ginkgo_biloba,b_for_ginkgo_biloba,b_to_b_for_ginkgo_biloba,
a_for_practicum_for_others_in_immortality_etc,b_for_practicum_for_others_in_immortality_etc,b_to_b_for_practicum_for_others_in_immortality_etc,
a_for_the_other_as,b_for_the_other_as,b_to_b_for_the_other_as,
a_for_thank_head_of_state,b_for_thank_head_of_state,b_to_b_for_thank_head_of_state,


a_for_immortality_medicine_for_memory,b_for_immortality_medicine_for_memory,b_to_b_for_immortality_medicine_for_memory,
a_for_body_replacement_for_memory,b_for_body_replacement_for_memory,b_to_b_for_body_replacement_for_memory,
a_for_anti_ageing_for_memory,b_for_anti_ageing_for_memory,b_to_b_for_anti_ageing_for_memory,
a_for_immortality_medicine_for_thinking,b_for_immortality_medicine_for_thinking,b_to_b_for_immortality_medicine_for_thinking,
a_for_body_replacement_for_thinking,b_for_body_replacement_for_thinking,b_to_b_for_body_replacement_for_thinking,
a_for_anti_ageing_for_thinking,b_for_anti_ageing_for_thinking,b_to_b_for_anti_ageing_for_thinking,
a_for_immortality_medicine_for_stopping_dementia,b_for_immortality_medicine_for_stopping_dementia,b_to_b_for_immortality_medicine_for_stopping_dementia,
a_for_body_replacement_for_stopping_dementia,b_for_body_replacement_for_stopping_dementia,b_to_b_for_body_replacement_for_stopping_dementia,
a_for_anti_ageing_for_stopping_dementia,b_for_anti_ageing_for_stopping_dementia,b_to_b_for_anti_ageing_for_stopping_dementia,
a_for_immortality_medicine_for_seeing_clearly,b_for_immortality_medicine_for_seeing_clearly,b_to_b_for_immortality_medicine_for_seeing_clearly,
a_for_body_replacement_for_seeing_clearly,b_for_body_replacement_for_seeing_clearly,b_to_b_for_body_replacement_for_seeing_clearly,
a_for_anti_ageing_for_seeing_clearly,b_for_anti_ageing_for_seeing_clearly,b_to_b_for_anti_ageing_for_seeing_clearly,
a_for_immortality_medicine_for_muscle_relaxation,b_for_immortality_medicine_for_muscle_relaxation,b_to_b_for_immortality_medicine_for_muscle_relaxation,
a_for_body_replacement_for_muscle_relaxation,b_for_body_replacement_for_muscle_relaxation,b_to_b_for_body_replacement_for_muscle_relaxation,
a_for_anti_ageing_for_muscle_relaxation,b_for_anti_ageing_for_muscle_relaxation,b_to_b_for_anti_ageing_for_muscle_relaxation,
a_for_immortality_medicine_for_circulatory_system__cardiovascular_system,b_for_immortality_medicine_for_circulatory_system__cardiovascular_system,b_to_b_for_immortality_medicine_for_circulatory_system__cardiovascular_system,
a_for_body_replacement_for_circulatory_system__cardiovascular_system,b_for_body_replacement_for_circulatory_system__cardiovascular_system,b_to_b_for_body_replacement_for_circulatory_system__cardiovascular_system,
a_for_anti_ageing_for_circulatory_system__cardiovascular_system,b_for_anti_ageing_for_circulatory_system__cardiovascular_system,b_to_b_for_anti_ageing_for_circulatory_system__cardiovascular_system,
a_for_immortality_medicine_for_digestive_system_and_excretory_system,b_for_immortality_medicine_for_digestive_system_and_excretory_system,b_to_b_for_immortality_medicine_for_digestive_system_and_excretory_system,
a_for_body_replacement_for_digestive_system_and_excretory_system,b_for_body_replacement_for_digestive_system_and_excretory_system,b_to_b_for_body_replacement_for_digestive_system_and_excretory_system,
a_for_anti_ageing_for_digestive_system_and_excretory_system,b_for_anti_ageing_for_digestive_system_and_excretory_system,b_to_b_for_anti_ageing_for_digestive_system_and_excretory_system,
a_for_immortality_medicine_for_endocrine_system,b_for_immortality_medicine_for_endocrine_system,b_to_b_for_immortality_medicine_for_endocrine_system,
a_for_body_replacement_for_endocrine_system,b_for_body_replacement_for_endocrine_system,b_to_b_for_body_replacement_for_endocrine_system,
a_for_anti_ageing_for_endocrine_system,b_for_anti_ageing_for_endocrine_system,b_to_b_for_anti_ageing_for_endocrine_system,
a_for_immortality_medicine_for_integumentary_system__exocrine_system,b_for_immortality_medicine_for_integumentary_system__exocrine_system,b_to_b_for_immortality_medicine_for_integumentary_system__exocrine_system,
a_for_body_replacement_for_integumentary_system__exocrine_system,b_for_body_replacement_for_integumentary_system__exocrine_system,b_to_b_for_body_replacement_for_integumentary_system__exocrine_system,
a_for_anti_ageing_for_integumentary_system__exocrine_system,b_for_anti_ageing_for_integumentary_system__exocrine_system,b_to_b_for_anti_ageing_for_integumentary_system__exocrine_system,
a_for_immortality_medicine_for_immune_system_and_lymphatic_system,b_for_immortality_medicine_for_immune_system_and_lymphatic_system,b_to_b_for_immortality_medicine_for_immune_system_and_lymphatic_system,
a_for_body_replacement_for_immune_system_and_lymphatic_system,b_for_body_replacement_for_immune_system_and_lymphatic_system,b_to_b_for_body_replacement_for_immune_system_and_lymphatic_system,
a_for_anti_ageing_for_immune_system_and_lymphatic_system,b_for_anti_ageing_for_immune_system_and_lymphatic_system,b_to_b_for_anti_ageing_for_immune_system_and_lymphatic_system,
a_for_immortality_medicine_for_muscular_system,b_for_immortality_medicine_for_muscular_system,b_to_b_for_immortality_medicine_for_muscular_system,
a_for_body_replacement_for_muscular_system,b_for_body_replacement_for_muscular_system,b_to_b_for_body_replacement_for_muscular_system,
a_for_anti_ageing_for_muscular_system,b_for_anti_ageing_for_muscular_system,b_to_b_for_anti_ageing_for_muscular_system,
a_for_immortality_medicine_for_nervous_system,b_for_immortality_medicine_for_nervous_system,b_to_b_for_immortality_medicine_for_nervous_system,
a_for_body_replacement_for_nervous_system,b_for_body_replacement_for_nervous_system,b_to_b_for_body_replacement_for_nervous_system,
a_for_anti_ageing_for_nervous_system,b_for_anti_ageing_for_nervous_system,b_to_b_for_anti_ageing_for_nervous_system,
a_for_immortality_medicine_for_renal_system_and_urinary_system,b_for_immortality_medicine_for_renal_system_and_urinary_system,b_to_b_for_immortality_medicine_for_renal_system_and_urinary_system,
a_for_body_replacement_for_renal_system_and_urinary_system,b_for_body_replacement_for_renal_system_and_urinary_system,b_to_b_for_body_replacement_for_renal_system_and_urinary_system,
a_for_anti_ageing_for_renal_system_and_urinary_system,b_for_anti_ageing_for_renal_system_and_urinary_system,b_to_b_for_anti_ageing_for_renal_system_and_urinary_system,
a_for_immortality_medicine_for_reproductive_system,b_for_immortality_medicine_for_reproductive_system,b_to_b_for_immortality_medicine_for_reproductive_system,
a_for_body_replacement_for_reproductive_system,b_for_body_replacement_for_reproductive_system,b_to_b_for_body_replacement_for_reproductive_system,
a_for_anti_ageing_for_reproductive_system,b_for_anti_ageing_for_reproductive_system,b_to_b_for_anti_ageing_for_reproductive_system,
a_for_immortality_medicine_for_respiratory_system,b_for_immortality_medicine_for_respiratory_system,b_to_b_for_immortality_medicine_for_respiratory_system,
a_for_body_replacement_for_respiratory_system,b_for_body_replacement_for_respiratory_system,b_to_b_for_body_replacement_for_respiratory_system,
a_for_anti_ageing_for_respiratory_system,b_for_anti_ageing_for_respiratory_system,b_to_b_for_anti_ageing_for_respiratory_system,
a_for_immortality_medicine_for_skeletal_system,b_for_immortality_medicine_for_skeletal_system,b_to_b_for_immortality_medicine_for_skeletal_system,
a_for_body_replacement_for_skeletal_system,b_for_body_replacement_for_skeletal_system,b_to_b_for_body_replacement_for_skeletal_system,
a_for_anti_ageing_for_skeletal_system,b_for_anti_ageing_for_skeletal_system,b_to_b_for_anti_ageing_for_skeletal_system,
a_for_immortality_medicine_for_antidepressant,b_for_immortality_medicine_for_antidepressant,b_to_b_for_immortality_medicine_for_antidepressant,
a_for_body_replacement_for_antidepressant,b_for_body_replacement_for_antidepressant,b_to_b_for_body_replacement_for_antidepressant,
a_for_anti_ageing_for_antidepressant,b_for_anti_ageing_for_antidepressant,b_to_b_for_anti_ageing_for_antidepressant,
a_for_immortality_medicine_for_antipsychotic,b_for_immortality_medicine_for_antipsychotic,b_to_b_for_immortality_medicine_for_antipsychotic,
a_for_body_replacement_for_antipsychotic,b_for_body_replacement_for_antipsychotic,b_to_b_for_body_replacement_for_antipsychotic,
a_for_anti_ageing_for_antipsychotic,b_for_anti_ageing_for_antipsychotic,b_to_b_for_anti_ageing_for_antipsychotic,

a_1_for_immortality_keeping_same_appearance_to_home,a_2_for_immortality_keeping_same_appearance_to_home,
a_3_for_immortality_keeping_same_appearance_to_home,
a_4_for_immortality_keeping_same_appearance_to_home,

school_teacher_a_1,
school_teacher_a_2,
school_teacher_a_3,
school_teacher_a_4,

medicine_a_1,
medicine_a_2,
medicine_a_3,
medicine_a_4,

bots_a_1,
bots_a_2,
bots_a_3,
bots_a_4,

sales_a_1,
sales_a_2,
sales_a_3,
sales_a_4,

if_a_teacher_then_seen_as_leading_a_country,

control_not_to_die,control_not_to_have_s_contact,control_not_to_leave_simulation,control_whether_appear_to_people,

can_t_be_involuntarily_time_travelled,

ai_and_ped_thoughts,

death_preventer,

announce_to_do_a_to_prevent_death_if_necessary,

fake_memory_identifier,
fake_memory_canceller



].
*/


% instead of ./bc12.sh change to
%cd Time_Machine
%swipl
%['bc12.pl'].
%bc12(5). % e.g. for 5 ./bc12.sh's
%halt

bc12(N) :- b(A),N1 is N+A,retractall(b(_)),assertz(b(N1)),!.
/*
bc12(0) :-!.
bc12(N):- bc12,N1 is N-1,bc12(N1),!.
bc12 :- texttobr2_2(64).
*/


texttobr2 :-
br1([[a,1,1.5,0],[about,1,1,0],[ache,1,0,0],[after,1,1,0],[all,1,1.5,0],[an,1,1.5,0],[and,1,1,0],[appearances,5,0,5],[apple,5,5,5],[are,1,1,0],[area,5,5,0],[argument,1,1.5,0],[as,1,1,0],[asanas,180,50,1],[at,1,1,0],[ate,15,2,1],[avoid,1,1,0],[b,1,1,1],[bacteria,2,1,1],[based,5,5,1],[be,50,30,180],[before,1,1,0],[being,50,30,180],[binding,1,1,0],[blocking,1,1,1],[bolt,2,1,1],[box,1,1,1],[breakfast,10,10,1],[breasoned,5,5,5],[breasoning,5,5,5],[breasonings,5,5,5],[by,1,1,0],[chapter,10,15,1],[clear,1,1,0],[colds,1,1,1],[comfort,180,50,30],[comfortable,50,50,100],[complexes,1,1,1],[conception,50,14,8],[connected,1,1,0],[correctness,1,1,0],[day,10,10,10],[depression,1,1,0],[details,1,1,1],[did,1,1,0],[do,50,30,180],[dotted,1,1,0],[down,1,1,0],[drinking,5,5,5],[during,1,1.5,0],[each,1,1,0],[earned,1,1.5,0],[education,50,30,180],[effects,1,1.5,0],[elderberries,1,1,1],[ensure,1,1,0],[excess,1,1,1],[exercises,10,10,1],[f,5,5,5],[feeling,1,1,0],[felt,1,1,0],[first,1,1.5,0],[flu,1,1,0],[food,2,1,1],[for,1,1,0],[from,1,1,0],[fruits,1,1,1],[function,1,1.5,0],[gaffer,10,10,1],[gave,1,1,1],[glasses,15,11,3],[god,50,30,180],[grade,1,1.5,0],[grains,1,1,1],[had,1,1,0],[hallucinogenic,1,1,0],[happiness,1,1,0],[happy,1,1,0],[have,5,5,5],[head,15,20,23],[headache,1,1,0],[headaches,1,1,0],[health,50,30,180],[healthy,50,30,180],[help,5,5,0],[helped,50,30,180],[high,1,1.5,0],[hills,5,5,2],[honey,10,10,10],[i,50,30,180],[imagery,5,5,0],[in,1,1,0],[incompatibility,1,1,0],[interpretation,20,30,0],[it,1,1,0],[keep,1,1,0],[laughter,1,1.5,0],[maintain,1,1,0],[maintaining,1,1,0],[master,50,30,180],[mind,3,4,4],[minutes,20,30,0],[mistake,1,1,0],[muscle,1,1,1],[muscles,1,1,1],[music,1,1,0],[must,1,1,0],[my,50,30,180],[namaskar,15,10,23],[neck,15,15,10],[next,1,1,0],[nietzsche,50,30,180],[no,1,1,0],[noticed,50,30,180],[nut,1,1,0],[nuts,1,1,1],[of,1,1,0],[off,1,1.5,0],[on,1,1,0],[one,1,1.5,0],[organs,1,1,1],[out,1,1,0],[over,1,1,0],[part,1,1,1],[peace,1,1.5,0],[perfect,1,1.5,0],[performed,50,30,180],[performing,50,30,250],[philosophy,10,20,1],[physiology,50,30,180],[pimple,1,1,0],[pm,5,5,5],[poem,1,1.5,0],[positive,1,1,0],[pot,5,5,10],[prayer,5,5,0],[prepared,1,1,0],[prevent,1,1,0],[prevented,1,1,0],[preventing,1,1,0],[prevention,1,1,0],[problems,1,1.5,0],[product,1,150,1],[products,5,5,5],[psychiatry,50,30,180],[psychology,2,2,0],[quality,1,1.5,0],[quantum,1,1,0],[read,15,1,20],[relax,180,50,30],[relaxed,180,50,30],[remain,1,1.5,0],[require,1,1,0],[room,500,400,300],[s,1,1,0],[safe,1,1.5,0],[sales,1,1.5,0],[same,1,1,0],[schizophrenia,1,1,0],[second,1,1.5,0],[see,1,0,1],[seek,1,1,0],[sell,5,3,0],[sets,5,1,0],[sex,1,1.5,0],[short,1,1,0],[single,1,1.5,0],[sites,20,0,30],[sitting,50,70,150],[sized,30,1,0],[skin,1,1,0],[sleep,180,50,30],[slices,2,2,2],[so,1,1,0],[societal,50,30,180],[some,1,1,0],[spine,1,1,10],[spiritual,50,30,180],[state,1,1.5,0],[stated,20,30,0],[stating,50,30,180],[status,1,1.5,0],[stop,5,1,15],[straight,1,1,0],[strawberry,1,1,1],[structure,1,1,1],[studied,50,30,180],[study,100,50,100],[studying,50,30,180],[subject,50,30,180],[successful,1,1.5,0],[surya,1,1.5,0],[sutra,5,1.5,0],[table,7,5,0],[tape,10,10,1],[task,15,2.5,0],[technique,1,1,0],[test,20,20,0],[text,20,30,0],[that,1,1,0],[the,1,1,0],[them,50,30,180],[then,1,1,0],[they,50,30,180],[thinking,1,1.5,0],[third,1,1.5,0],[this,1,1,0],[thoughts,1,1,0],[through,1,1,0],[tied,1,1,0],[time,1,1.5,0],[to,1,1,0],[together,1,1,0],[touch,1,1,0],[train,1,1,1],[trains,50,30,180],[travel,10,3,0],[treating,20,15,3],[turn,1,1,0],[two,1,1.5,0],[university,100,75,3],[unwanted,1,1,0],[up,1,1,0],[upasana,100,75,100],[used,1,1,0],[using,1,1,0],[var,1,1,1],[vegetables,5,5,5],[videos,5,0,3],[view,5,5,5],[virality,1,1,0],[viruses,1,1,2],[vitamin,1,1,1],[walks,100,500,0],[wanted,15,20,3],[warm,1,1,0],[was,1,1,0],[water,5,5,5],[way,1,1,0],[ways,50,100,0],[well,50,30,180],[where,1,1,0],[whole,1,1,1],[with,1,1,0],[without,1,1,0],[words,5,7,1],[write,15,1,1],[writing,5,5,0],[wrote,15,1,1],[years,3,1,0]]).

br1([[a,1,1.5,0],[about,1,1,0],[ache,1,0,0],[after,1,1,0],[all,1,1.5,0],[an,1,1.5,0],[and,1,1,0],[appearances,5,0,5],[apple,5,5,5],[are,1,1,0],[area,5,5,0],[argument,1,1.5,0],[as,1,1,0],[asanas,180,50,1],[at,1,1,0],[ate,15,2,1],[avoid,1,1,0],[b,1,1,1],[bacteria,2,1,1],[based,5,5,1],[be,50,30,180],[before,1,1,0],[being,50,30,180],[binding,1,1,0],[blocking,1,1,1],[bolt,2,1,1],[box,1,1,1],[breakfast,10,10,1],[breasoned,5,5,5],[breasoning,5,5,5],[breasonings,5,5,5],[by,1,1,0],[chapter,10,15,1],[clear,1,1,0],[colds,1,1,1],[comfort,180,50,30],[comfortable,50,50,100],[complexes,1,1,1],[conception,50,14,8],[connected,1,1,0],[correctness,1,1,0],[day,10,10,10],[depression,1,1,0],[details,1,1,1],[did,1,1,0],[do,50,30,180],[dotted,1,1,0],[down,1,1,0],[drinking,5,5,5],[during,1,1.5,0],[each,1,1,0],[earned,1,1.5,0],[education,50,30,180],[effects,1,1.5,0],[elderberries,1,1,1],[ensure,1,1,0],[excess,1,1,1],[exercises,10,10,1],[f,5,5,5],[feeling,1,1,0],[felt,1,1,0],[first,1,1.5,0],[flu,1,1,0],[food,2,1,1],[for,1,1,0],[from,1,1,0],[fruits,1,1,1],[function,1,1.5,0],[gaffer,10,10,1],[gave,1,1,1],[glasses,15,11,3],[god,50,30,180],[grade,1,1.5,0],[grains,1,1,1],[had,1,1,0],[hallucinogenic,1,1,0],[happiness,1,1,0],[happy,1,1,0],[have,5,5,5],[head,15,20,23],[headache,1,1,0],[headaches,1,1,0],[health,50,30,180],[healthy,50,30,180],[help,5,5,0],[helped,50,30,180],[high,1,1.5,0],[hills,5,5,2],[honey,10,10,10],[i,50,30,180],[imagery,5,5,0],[in,1,1,0],[incompatibility,1,1,0],[interpretation,20,30,0],[it,1,1,0],[keep,1,1,0],[laughter,1,1.5,0],[maintain,1,1,0],[maintaining,1,1,0],[master,50,30,180],[mind,3,4,4],[minutes,20,30,0],[mistake,1,1,0],[muscle,1,1,1],[muscles,1,1,1],[music,1,1,0],[must,1,1,0],[my,50,30,180],[namaskar,15,10,23],[neck,15,15,10],[next,1,1,0],[nietzsche,50,30,180],[no,1,1,0],[noticed,50,30,180],[nut,1,1,0],[nuts,1,1,1],[of,1,1,0],[off,1,1.5,0],[on,1,1,0],[one,1,1.5,0],[organs,1,1,1],[out,1,1,0],[over,1,1,0],[part,1,1,1],[peace,1,1.5,0],[perfect,1,1.5,0],[performed,50,30,180],[performing,50,30,250],[philosophy,10,20,1],[physiology,50,30,180],[pimple,1,1,0],[pm,5,5,5],[poem,1,1.5,0],[positive,1,1,0],[pot,5,5,10],[prayer,5,5,0],[prepared,1,1,0],[prevent,1,1,0],[prevented,1,1,0],[preventing,1,1,0],[prevention,1,1,0],[problems,1,1.5,0],[product,1,150,1],[products,5,5,5],[psychiatry,50,30,180],[psychology,2,2,0],[quality,1,1.5,0],[quantum,1,1,0],[read,15,1,20],[relax,180,50,30],[relaxed,180,50,30],[remain,1,1.5,0],[require,1,1,0],[room,500,400,300],[s,1,1,0],[safe,1,1.5,0],[sales,1,1.5,0],[same,1,1,0],[schizophrenia,1,1,0],[second,1,1.5,0],[see,1,0,1],[seek,1,1,0],[sell,5,3,0],[sets,5,1,0],[sex,1,1.5,0],[short,1,1,0],[single,1,1.5,0],[sites,20,0,30],[sitting,50,70,150],[sized,30,1,0],[skin,1,1,0],[sleep,180,50,30],[slices,2,2,2],[so,1,1,0],[societal,50,30,180],[some,1,1,0],[spine,1,1,10],[spiritual,50,30,180],[state,1,1.5,0],[stated,20,30,0],[stating,50,30,180],[status,1,1.5,0],[stop,5,1,15],[straight,1,1,0],[strawberry,1,1,1],[structure,1,1,1],[studied,50,30,180],[study,100,50,100],[studying,50,30,180],[subject,50,30,180],[successful,1,1.5,0],[surya,1,1.5,0],[sutra,5,1.5,0],[table,7,5,0],[tape,10,10,1],[task,15,2.5,0],[technique,1,1,0],[test,20,20,0],[text,20,30,0],[that,1,1,0],[the,1,1,0],[them,50,30,180],[then,1,1,0],[they,50,30,180],[thinking,1,1.5,0],[third,1,1.5,0],[this,1,1,0],[thoughts,1,1,0],[through,1,1,0],[tied,1,1,0],[time,1,1.5,0],[to,1,1,0],[together,1,1,0],[touch,1,1,0],[train,1,1,1],[trains,50,30,180],[travel,10,3,0],[treating,20,15,3],[turn,1,1,0],[two,1,1.5,0],[university,100,75,3],[unwanted,1,1,0],[up,1,1,0],[upasana,100,75,100],[used,1,1,0],[using,1,1,0],[var,1,1,1],[vegetables,5,5,5],[videos,5,0,3],[view,5,5,5],[virality,1,1,0],[viruses,1,1,2],[vitamin,1,1,1],[walks,100,500,0],[wanted,15,20,3],[warm,1,1,0],[was,1,1,0],[water,5,5,5],[way,1,1,0],[ways,50,100,0],[well,50,30,180],[where,1,1,0],[whole,1,1,1],[with,1,1,0],[without,1,1,0],[words,5,7,1],[write,15,1,1],[writing,5,5,0],[wrote,15,1,1],[years,3,1,0]]).

texttobr2_2(0):-!.
texttobr2_2(N1):-
	texttobr2,N2 is N1-1,texttobr2_2(N2),!.